apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  selector:
    app: calculator
  ports:
    - protocol: TCP
      port: 30323
      targetPort: 3000  # The port the container is exposing
  type: NodePort